apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k36andzin-nodejs
  janus-idp.io/tekton: k36andzin-nodejs
  backstage.io/kubernetes-id: k36andzin-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: k36andzin-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
